### ISSUE TITLE
Bug - fibonacci 

### ISSUE THREAD

**Issue by harshays** [donnemartin/interactive-coding-challenges#1]
in ./recursion_dynamic/fibonacci/fibonacci_challenge.ipynb
<hr>
### currently

Test Cases
n = 0 -> 0
n = 1 -> 0
n > 1 -> 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...

### should be

Test Cases
n = 0 -> 0
n = 1 -> 1
n > 1 -> 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...

**Comment by donnemartin** [comment]
Nice catch...thanks for the bug report.  Do you want to submit a pull request? :)

Otherwise I'm happy to submit a fix.

**Comment by donnemartin** [comment]
The same issue can be found in the solution notebook:
fibonacci_solution.ipynb
