### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by Chun-Yang** [donnemartin/interactive-coding-challenges#11]
Thank you for your awesome challenges.

I am new to python, I know there is ```print``` and  ```pdb.set_trace()```.

1. Could you tell me where is the printed message?
2. And how to make pdb.set_trace() work?

**Comment by donnemartin** [comment]
Hi Chun-Yang, to debug just add the following line to the **Code** cell where you want the debugger to start:

```
import pdb; pdb.set_trace()
```

For example, you would add it like this:

```
def unique_chars_hash(string):
    import pdb; pdb.set_trace() # Start debugger when this line is hit
    chars_set = set()
    for char in string:
        if char in chars_set:
            return False
        else:
            chars_set.add(char)
    return True
```

Then run **both** the **Code** and **Unit Test** cells (either through the menu "Cell", or through a shortcut such as [shift + enter] or [control + enter].

This will put you into the pdb debugger where you can issue command like the following to l(ist) the source code:

```
l
```

or s(tep):

```
s
```

For a list of all commands, refer to this [link](https://docs.python.org/2/library/pdb.html#debugger-commands).
