### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by jstnlef** [donnemartin/interactive-coding-challenges#14]
It may be worth including a requirements.txt to this repository so that it's easy to install all the necessary dependancies in a virtualenv.

**Comment by donnemartin** [comment]
Justin,

Great idea, thanks for the suggestion and pull request.  I'll try to check it out in the next day or so.

-Donne

**Comment by jstnlef** [comment]
Thanks for this. It's definitely a wonderful interview prep tool.

**Comment by donnemartin** [comment]
Justin, thanks for the contribution!  Closing...merged pull request #15 to fix this issue.
