### ISSUE TITLE
Bug in Compress a string notebook?

### ISSUE THREAD

**Issue by cswarth** [donnemartin/interactive-coding-challenges#2]
The compress_string notebook as the following test cases:

- None -> None
- '' -> ''
- 'AABBCC' -> 'AABBCC'
- 'AAABCCDDDD' -> 'A3B1C2D4'

Shouldn't the third test case result be A2B2C2?
If not then the description of this challenge needs some more details on how this result is consistent with the last test result.

**Comment by donnemartin** [comment]
I think the problem statement could use some tweaking to help clarify the test cases.  Currently case #3 is explained by:

Constraints:
* Do you compress even if it doesn't save space?
    * No

Algorithm:
* Calculate the size of the compressed string
    * Note the constraint about compressing only if it saves space

Code:
```
    # If the compressed string size is greater than 
    # or equal to string size, return string
    if size >= len(string):
        return string
```

I'll submit a fix that updates the problem statement.

**Comment by donnemartin** [comment]
@cswarth thanks for reporting this issue!
