### ISSUE TITLE
partitioning linked list problem: Does not work if item greater than partition value is to the left.

### ISSUE THREAD

**Issue by masasin** [donnemartin/interactive-coding-challenges#21]
For instance:

        # Partition = 10
        # Input: 4, 3, 13, 8, 10, 1, 10, 12
        # Output: 4, 3, 8, 1, 10, 10, 13, 12

fails.

**Comment by donnemartin** [comment]
Hi Nassar-san,

Nice catch!  I've submitted a fix for this issue and updated the unit tests.

-Donne
