### ISSUE TITLE
Python3.6: Error when installing packages with pip install -r requirements.txt

### ISSUE THREAD

**Issue by DanielPerezJensen** [donnemartin/interactive-coding-challenges#240]
I'm using python3.6 and when I ran pip install -r requirements.txt to install all required packages the notebook did not work properly. When opening a notebook from the project I got this error: 
`/usr/bin/python: no module named ipykernel_launcher`

Upon googling this issue I found the advice to reinstall this packages so I ran:
```
pip3 uninstall ipykernel_launcher
pip3 install ipykernel_launcher
```

This fixed that import issue, but when I proceeded to open a notebook I got this error: 
`ImportError: cannot import name 'generator_to_async_generator'`

This did not have an easy fix on the internet, so I basically uninstalled all installed packages by running:

`pip3 uninstall -r requirements.txt
`
and proceeded to install jupyter notebook with pip by running:

`pip3 install jupyter`

This seems to have fixed the issue, all notebooks I have tried so far have worked without issue. But I feel this should be added in the README or did I do something wrong?

**Comment by donnemartin** [comment]
@DanielPerezJensen thanks for reporting!  I've fixed this with #241.
