### ISSUE TITLE
Issue with Pythonic Solution for reverse_string

### ISSUE THREAD

**Issue by anthonyattard** [donnemartin/interactive-coding-challenges#256]
The following solution does not work:
```
class ReverseStringAlt(object):

    def reverse_string_alt(string):
        if string:
            return string[::-1]
        return string

    def reverse_string_alt2(string):
        if string:
            return ''.join(reversed(string))
        return string
```

**Comment by Harshavika** [comment]
class ReverseStringAlt(object):
    def reverse_string_alt(self,string):
        if string:
            return string[::-1]
        return string

    
a=ReverseStringAlt()
s=input()
k=a.reverse_string_alt(s)
print(k)

**Comment by anthonyattard** [comment]
@Harshavika is my solution correct?

**Comment by rizveeerprojects** [comment]
@anthonyattard , this is your code which I just changed a little bit to run which gives correct answer.
[https://ideone.com/Tm5EE0](https://ideone.com/Tm5EE0).
