### ISSUE TITLE
Small phrasing fix

### ISSUE THREAD

**Issue by rafadaguiar** [donnemartin/interactive-coding-challenges#33]
In /stacks_queues/sort_stack/sort_stack_solution.ipynb there's a small phrasing issue on the line:
"While buffer is empty or buffer top is > than temp\n".

It should be "While buffer is **not** empty or buffer top is > than temp\n" as implied in the code below:

```Python
class MyStack(Stack):

    def sort(self):
        buff = MyStack()
        while not self.is_empty():
            temp = self.pop()
            while not buff.is_empty() and buff.peek() > temp:
                self.push(buff.pop())
            buff.push(temp)
        return buff
```

**Comment by donnemartin** [comment]
Hi Rafael,

Good catch, would you like to submit a PR?  Otherwise I'm happy to fix it.

-Donne
