### ISSUE TITLE
A bug in the check_balance solution

### ISSUE THREAD

**Issue by superxiao** [donnemartin/interactive-coding-challenges#35]
It fails for a tree like this:

                    3
               /        \
           2              5
         /             /        \
      1             4          6
                                    \
                                     7
This is not a balanced tree, but the solution returns True.

**Comment by donnemartin** [comment]
@superxiao thanks for the bug report!  Are you interested in submitting a pull request?  If not I'm happy to take a look and try to fix it.

**Comment by superxiao** [comment]
Sure, let me try.

**Comment by donnemartin** [comment]
Great, looking forward to a pull request :)
