### ISSUE TITLE
may compressing a string challenge improved?

### ISSUE THREAD

**Issue by muatik** [donnemartin/interactive-coding-challenges#38]
In  http://nbviewer.ipython.org/github/donnemartin/interactive-coding-challenges/blob/master/arrays_strings/rotation/rotation_challenge.ipynb, I think that for better compressing single characters may be left as they are. For example "AAABCCDDDD" is expected to be compressed as "A3B1C2D4"; however, "A3BCCD4" looks like to me a better compressing.

**Comment by donnemartin** [comment]
@muatik good catch, interested in submitting a pull request? :)

**Comment by hashhar** [comment]
Hey, @donnemartin, in case @muatik isn't working on this, may I try? I am comparatively new to python and think that this is on my level.

**Comment by muatik** [comment]
I will prepare a pull request @donnemartin 

@hashhar you should try. each person may accomplish a task differently, sometimes in a better way. 

if you are interested in my solution, you can follow this link: https://github.com/muatik/my-coding-challenges/blob/master/challenges-string-compress.ipynb

**Comment by hashhar** [comment]
@muatik Thanks. I'll try on my own and if I seem to get stuck, I'll see.

**Comment by donnemartin** [comment]
Great, looks like you guys sorted this out :+1:

**Comment by donnemartin** [comment]
Merged https://github.com/donnemartin/interactive-coding-challenges/pull/39.
